name: Run Video Script Daily

on:
  schedule:
    - cron: "30 22 * * *" # 4:00 AM IST
    - cron: "0 6 * * *"   # 11:30 AM IST
    - cron: "0 10 * * *"  # 3:30 PM IST
    - cron: "0 14 * * *"  # 7:30 PM IST
  workflow_dispatch:       # manual run option

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python main.py
